### PR TITLE
no error when deleting a class of an object in an objective due to th…

### LINKED ISSUE #100: Error when deleting Object Instances
When deleting a class in the data model, there are two errors ("OdTreeWalker.js:83 Error: element <om:Object id="Object_1v21jng" /> referenced by <om:Link id="Link_1l95ocq" />#targetRef not yet drawn" and "failed to import <om:Link id="Link_1maeft5" />") when an object instance of this class in the Objective Model will be deleted too because of the deletion in the data model.

1. What is the expected behaviour: Already has the expected behavior, but we don´t want to have an error in the console.
3. If not VERY clear: Why is this a problem

## Steps For Reproduction

1. go to Objective Model and in Objective
2. build two Object Instances that are linked
3. delete one of the corresponding classes from the Object Instances in the data model --> error is thrown

### PR DESCRIPTION
**Pull request by mariejarisch**
Fixes #100

no error when deleting the class of an object in an objective anymore

## PR checklist

- [x] dev-branch has been merged into local branch to resolve conflicts
- [x] the application has been manually tested after merge
- [x] another dev reviewed and approved
- [x] if feature-Branch: Teams PO has approved (show via e.g. screenshots/screencapture/live demo)

### CODE REVIEW

File: app/lib/objectivemodeler/OmModeler.js [hunk 1]
```diff
@@ -319,3 +320,10 @@ OmModeler.prototype.getObjectiveByReference = function (objectiveReference) {
     }
 }
 
+OmModeler.prototype.isObjectOfDeletedClass = function (clazz, element) {
+    return is(element, 'om:Object') && clazz.id && element.classRef?.id === clazz.id;
+}
+
+OmModeler.prototype.isLinkConnectedToObjectOfDeletedClass = function (clazz, element) {
+    return is(element, 'om:Link') && clazz.id && ((element.sourceRef?.classRef.id === clazz.id) || (element.targetRef?.classRef.id === clazz.id));
```
Comment (Firsttryy) [inline app/lib/objectivemodeler/OmModeler.js:328]: ? hinter classRef bitte, damit keine undefined errors fliegen

**Review by Firsttryy — CHANGES_REQUESTED** [review]
